name: parky
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  easy_localization: ^3.0.7
  either_dart: ^1.0.0
  equatable: ^2.0.5
  favorite_button: ^0.0.4
  file_picker: ^9.0.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_bounceable: ^1.2.0
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.2.0
  google_maps_flutter: ^2.10.0
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  location: ^8.0.0
  lottie: ^3.3.1
  page_transition: ^2.1.0
  permission_handler: ^11.3.1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.3
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/icons/
    - assets/translations/
    - shorebird.yaml
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
