// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK_u1yMXEBJIK8f9W7EjIroT_5H29cYi0',
    appId: '1:1093245125957:web:ad7a1feef20438c0482a2c',
    messagingSenderId: '1093245125957',
    projectId: 'parky-a7746',
    authDomain: 'parky-a7746.firebaseapp.com',
    storageBucket: 'parky-a7746.firebasestorage.app',
    measurementId: 'G-93YEYHNCBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrVPdJnS0FCbexgRPAsRsAAZJmgUZQuc',
    appId: '1:1093245125957:android:ec8369e3e23a3c62482a2c',
    messagingSenderId: '1093245125957',
    projectId: 'parky-a7746',
    storageBucket: 'parky-a7746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHhFGCZOglq1IT51BjjB1nanvvwciWBc',
    appId: '1:1093245125957:ios:ea10c2890296137e482a2c',
    messagingSenderId: '1093245125957',
    projectId: 'parky-a7746',
    storageBucket: 'parky-a7746.firebasestorage.app',
    iosBundleId: 'com.example.newStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoHhFGCZOglq1IT51BjjB1nanvvwciWBc',
    appId: '1:1093245125957:ios:ea10c2890296137e482a2c',
    messagingSenderId: '1093245125957',
    projectId: 'parky-a7746',
    storageBucket: 'parky-a7746.firebasestorage.app',
    iosBundleId: 'com.example.newStructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK_u1yMXEBJIK8f9W7EjIroT_5H29cYi0',
    appId: '1:1093245125957:web:3d0b945eb0c23a75482a2c',
    messagingSenderId: '1093245125957',
    projectId: 'parky-a7746',
    authDomain: 'parky-a7746.firebaseapp.com',
    storageBucket: 'parky-a7746.firebasestorage.app',
    measurementId: 'G-0F6JKD649L',
  );
}
